### ISSUE TITLE
GitHub Action build.yml

### ISSUE THREAD

**Issue by xmnlab** [thegraphnetwork/epigraphhub_py#69]
the current build.yml has the following steps:

```yaml
    - name: Run style checks
      run: |
        make check-codestyle
    - name: Run tests
      run: |
        make test
    - name: Run safety checks
      run: |
        make check-safety
```

as tests are more critical than the code style check, I think it could be executed first.
and for code style check and safety check, they could be executed also if the tests failed, because they are independent.

Proposal:

```yaml
    - name: Run tests
      run: |
        make test
        
    - name: Run style checks
      if: always()
      run: |
        make check-codestyle

    - name: Run safety checks
      if: always()
      run: |
        make check-safety
```

@fccoelho any thoughts about that?
